name: Deploy

on:
  push:
    branches:
      - master
      - develop

env:
  AWS_REGION: eu-west-3

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define variables
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy on prod
        if: github.ref == 'refs/heads/master'
        run: bash ./infra/deploy.sh dev

      - name: Deploy on dev
        if: github.ref == 'refs/heads/develop'
        run: bash ./infra/deploy.sh dev
