name: Deploy
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
env:
  AWS_REGION: eu-west-3
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_TEST_URL }}
  LOG_LEVEL: debug
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
  build:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Remove dist folder
        run: rm -rf ./dist
      - name: Compile src
        run: yarn compile
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy on prod
        if: github.ref == 'refs/heads/master'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LOG_LEVEL: 'info'
        run: bash ./infra/deploy.sh prod
      - name: Deploy on dev
        if: github.ref == 'refs/heads/develop'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_DEV_URL }}
          LOG_LEVEL: 'info'
        run: bash ./infra/deploy.sh dev
